name: Feature Request
description: Suggest a new feature for {{ PROJECT_NAME }}
title: "[Feature] "
labels: ["enhancement", "needs-discussion"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide detailed information to help us understand your proposal.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission checklist
      options:
        - label: I have searched existing issues and discussions
          required: true
        - label: I have reviewed the project roadmap
          required: true
        - label: This feature aligns with the project's goals
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: Describe the problem or limitation you're experiencing...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: What would you like to see implemented?
      placeholder: Describe your proposed solution...
    validations:
      required: true

  - type: textarea
    id: use_case
    attributes:
      label: Use Case
      description: How would this feature be used in genomics research?
      placeholder: |
        Describe specific research scenarios where this feature would be valuable:
        - Analysis type: [e.g., GWAS, imputation, population genetics]
        - Data context: [e.g., large cohorts, rare variants, multi-ancestry]
        - Workflow integration: [e.g., with existing tools, pipelines]
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature for your research?
      options:
        - Critical - blocking research progress
        - High - would significantly improve workflow
        - Medium - would be nice to have
        - Low - minor convenience improvement
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered other approaches?
      placeholder: Describe alternative solutions or workarounds you've considered...
    validations:
      required: false

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Ideas
      description: Do you have ideas about how this could be implemented?
      placeholder: |
        If you have technical ideas about implementation:
        - Algorithm suggestions
        - Library recommendations  
        - Performance considerations
        - Compatibility requirements
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I would be willing to contribute to implementing this feature
        - label: I can help with testing and validation
        - label: I can provide sample data for testing
        - label: I can help with documentation

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other relevant information
      placeholder: Add any other context, screenshots, or references...
    validations:
      required: false